---
lang: es
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T)
```

# Medidas centrales y medidas de dispersión: la media y la varianza.

Al estudiar el diagrama de caja (_boxplot_) hemos visto que este gráfico se describe mediante los **cinco números**, que son:

- mínimo y máximo,  
- primer y tercer cuartil (25% y 75%), y 
- segundo cuartil (50%). 

De estos valores, el segundo cuartil, que se corresponde con la mitad de los valores, representa una estimación del centro de la distribución, y por eso lo llamamos **mediana**. La distancia entre el primer y tercer cuartil es lo que se conoce como **rango intercuartil** (se suele representar por sus siglas en inglés, **IQR**), y nos da una indicación de la **dispersión**: cuanto mayor mayor es la dispersión de nuestros valores, más alejados estarán del centro, y por lo tanto habrá mayor distancia entre el primer y el tercer cuartil. 

Una de las mayores ventajas de la mediana y del rango intercuartil es que son estadísticos robustos, es decir, tiene una alta robustez a los valores atípicos. Como en el cálculo del rango intercuartil no se tienen en cuenta los valores extremos, su valor variará muy poco si aparecen nuevas observaciones atípicas (outliers). Como sus valores no dependen de la distribución de los datos, a estos estadísticos se los conoce como **no paramétricos**.

Existen otras estadísticos, llamados **paramétricos**, que, en determinadas condiciones, tienen ventajas frente a los no paramétricos. Los principales son la **media aritmética**, o simplemente, **media**, y la **varianza**.

## La media aritmética: un ejemplo de cálculo.

