project:
  type: book
  output-dir: docs

book:
  title: "Introducción al análisis de datos industriales utilizando Microsoft Excel y R"
  subtitle: "Manual para la Formación Profesional"
  author: "Juan Riera"
  date: 2025-02-22
  date-format: short
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Introducción"
      chapters:
        - 010-intro.qmd
        - 020-herramientas.qmd   
    - part: "Técnicas básicas"
      chapters:
        - 030-organizacion.qmd  
        - 040-exploracion.qmd
        - 050-estad-simple.qmd
        - 060-forma-de-los-datos.qmd
        - 070-relacion-xy.qmd
        - 080-comunicacion.qmd
    - part: "Conceptos avanzados"
      chapters:
        - 090-distr-prob.qmd
        - 100-anova.qmd
        - 110-disexp.qmd
    - part: "Aplicaciones prácticas"
      chapters:
        - 120-control-proc.qmd
        - 130-sistema-medicion.qmd
        - 140-mejora-procesos.qmd
  appendices: 
    - 150-anexo-R.qmd
    - 160-bibliografia.qmd

language:
  section-title-appendices: "Anexos"
  section-title-bibliography: "Bibliografía"

number-depth: 2

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
