project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la estadística industrial y la ciencia de datos utilizando Microsoft Excel y R"
  subtitle: "Manual para la Formación Profesional"
  author: "Juan Riera"
  date: 2024-05
  date-format: short
  chapters:
    - index.qmd
    - 010-intro.qmd
    - 020-herramientas.qmd   
    - 030-organizacion.qmd  
    - 040-exploracion.qmd
    - 050-estad-simple.qmd
    - 060-forma-de-los-datos.qmd
    - 070-distr-prob.qmd
    - 080-relacion-xy.qmd
    - 090-anova.qmd
    - 100-sistema-medicion.qmd
    - 110-control-proc.qmd
    - 120-disexp.qmd
    - 130-comunicacion.qmd
    - 140-mejora-calidad.qmd
    - 150-anexo-R.qmd
    - 160-bibliografia.qmd

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
