project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la estadística industrial y la ciencia de datos utilizando Microsoft Excel y R"
  subtitle: "Manual para la Formación Profesional"
  author: "Juan Riera"
  date: 2022-12-12
  date-format: short
  chapters:
    - index.qmd
    - 010-intro.qmd
    - 020-datos-industriales.qmd
    - 030-herramientas-1-hoja.qmd    
    - 035-herramientas-2-R.qmd    
    - 040-distr-frec-explor.qmd
    - 050-distr-prob.qmd
    - 060-relacion-xy.qmd
    - 070-anova.qmd
    - 080-sistema-medicion.qmd
    - 090-control-proc.qmd
    - 100-disexp.qmd
    - 110-mejora-calidad.qmd
    - 120-anexo-metodos.qmd
    - 130-bibliografia.qmd

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
