project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la estadística industrial y la ciencia de datos utilizando Microsoft Excel y R"
  subtitle: "Manual para la Formación Profesional"
  author: "Juan Riera"
  date: 2022-12-12
  date-format: short
  chapters:
    - index.qmd
    - 010-intro.qmd
    - 020-herramientas.qmd
    - 030-prep-datos.qmd    
    - 040-distr-frec-explor.qmd
    - 050-distr-prob.md
    - 060-relacion-xy.md
    - 070-anova.md
    - 080-sistema-medicion.md
    - 090-control-proc.md
    - 100-disexp.md
    - 110-mejora-calidad.md
    - 120-anexo-metodos.md
    - 130-bibliografia.qmd

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrbook

author-title: AUTOR
published-title: PUBLICADO
