project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la estadística industrial y la ciencia de datos utilizando Microsoft Excel y R"
  subtitle: "Manual para la Formación Profesional"
  author: "Juan Riera"
  date: 2024-05
  date-format: short
  chapters:
    - index.qmd
    - 010-intro.qmd
    - 020-herramientas.qmd   
    - part: "Técnicas básicas"
      chapters:
        - 030-organizacion.qmd  
        - 040-exploracion.qmd
        - 050-estad-simple.qmd
        - 060-forma-de-los-datos.qmd
        - 070-distr-prob.qmd
        - 080-relacion-xy.qmd
        - 090-anova.qmd
        - 100-comunicacion.qmd
    - part: "Aplicaciones prácticas"
      chapters:
        - 110-sistema-medicion.qmd
        - 120-control-proc.qmd
        - 130-disexp.qmd
        - 140-mejora-procesos.qmd
  appendices: 
    - 150-anexo-R.qmd
    - 160-bibliografia.qmd

language:
  section-title-appendices: "Anexos"
  section-title-bibliography: "Bibliografía"

number-depth: 2

bibliography: bibliografia.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: book

author-title: AUTOR
published-title: PUBLICADO
